ALTER TABLE places
    ADD COLUMN source_category_name VARCHAR(500),
    ADD COLUMN source_category_group_code VARCHAR(20);

CREATE TABLE place_category_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(100) NOT NULL,
    target_place_type VARCHAR(20) NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_place_category_rules_keyword UNIQUE (keyword),
    CONSTRAINT ck_place_category_rules_place_type CHECK (
        target_place_type IN ('ACTIVITY', 'MEAL', 'CAFE')
    )
);

CREATE INDEX idx_place_category_rules_active_priority
    ON place_category_rules (is_active, priority DESC, id);

INSERT INTO place_category_rules (keyword, target_place_type, priority)
VALUES
    ('방탈출카페', 'ACTIVITY', 100),
    ('보드게임카페', 'ACTIVITY', 100),
    ('보드카페', 'ACTIVITY', 100),
    ('키즈카페', 'ACTIVITY', 100);

INSERT INTO place_collection_profiles (provider, code, name, search_type, query, place_type)
VALUES
    ('KAKAO', 'ESCAPE_ROOM', '방탈출', 'KEYWORD', '방탈출', 'ACTIVITY'),
    ('KAKAO', 'BOARD_GAME', '보드게임', 'KEYWORD', '보드게임', 'ACTIVITY'),
    ('KAKAO', 'KIDS_CAFE', '키즈카페', 'KEYWORD', '키즈카페', 'ACTIVITY'),
    ('KAKAO', 'EXHIBITION', '전시', 'KEYWORD', '전시', 'ACTIVITY'),
    ('KAKAO', 'POPUP', '팝업', 'KEYWORD', '팝업', 'ACTIVITY'),
    ('KAKAO', 'BOOKSTORE', '서점', 'KEYWORD', '서점', 'ACTIVITY'),
    ('KAKAO', 'SHOPPING', '쇼핑', 'KEYWORD', '쇼핑', 'ACTIVITY');
