CREATE TABLE cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_cities_code UNIQUE (code)
);

CREATE TABLE areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    collection_center_latitude NUMERIC(10, 7) NOT NULL,
    collection_center_longitude NUMERIC(10, 7) NOT NULL,
    collection_min_latitude NUMERIC(10, 7) NOT NULL,
    collection_min_longitude NUMERIC(10, 7) NOT NULL,
    collection_max_latitude NUMERIC(10, 7) NOT NULL,
    collection_max_longitude NUMERIC(10, 7) NOT NULL,
    CONSTRAINT fk_areas_city FOREIGN KEY (city_id) REFERENCES cities (id),
    CONSTRAINT uk_areas_city_code UNIQUE (city_id, code),
    CONSTRAINT ck_areas_collection_latitude_range CHECK (collection_min_latitude <= collection_center_latitude AND collection_center_latitude <= collection_max_latitude),
    CONSTRAINT ck_areas_collection_longitude_range CHECK (collection_min_longitude <= collection_center_longitude AND collection_center_longitude <= collection_max_longitude)
);

CREATE TABLE places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(30) NOT NULL,
    provider_place_id VARCHAR(100) NOT NULL,
    area_id BIGINT NOT NULL,
    place_type VARCHAR(20) NOT NULL,
    name VARCHAR(200) NOT NULL,
    address_name VARCHAR(500),
    road_address_name VARCHAR(500),
    latitude NUMERIC(10, 7) NOT NULL,
    longitude NUMERIC(10, 7) NOT NULL,
    place_url VARCHAR(1000),
    phone VARCHAR(50),
    is_anchor_candidate BOOLEAN NOT NULL DEFAULT FALSE,
    selection_count BIGINT NOT NULL DEFAULT 0,
    last_selected_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    operating_hours VARCHAR(1000),
    operating_days VARCHAR(500),
    last_synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_places_area FOREIGN KEY (area_id) REFERENCES areas (id),
    CONSTRAINT uk_places_provider_place_id UNIQUE (provider, provider_place_id),
    CONSTRAINT ck_places_provider CHECK (provider IN ('KAKAO', 'TOUR')),
    CONSTRAINT ck_places_place_type CHECK (place_type IN ('ACTIVITY', 'FOOD', 'CAFE')),
    CONSTRAINT ck_places_selection_count_non_negative CHECK (selection_count >= 0)
);

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    CONSTRAINT uk_tags_code UNIQUE (code)
);

CREATE TABLE area_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    weight INTEGER NOT NULL,
    CONSTRAINT fk_area_tags_area FOREIGN KEY (area_id) REFERENCES areas (id),
    CONSTRAINT fk_area_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id),
    CONSTRAINT uk_area_tags_area_tag UNIQUE (area_id, tag_id),
    CONSTRAINT ck_area_tags_weight CHECK (weight BETWEEN 0 AND 100)
);

CREATE TABLE place_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    weight INTEGER NOT NULL,
    CONSTRAINT fk_place_tags_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT fk_place_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id),
    CONSTRAINT uk_place_tags_place_tag UNIQUE (place_id, tag_id),
    CONSTRAINT ck_place_tags_weight CHECK (weight BETWEEN 0 AND 100)
);

CREATE INDEX idx_areas_city_id ON areas (city_id);
CREATE INDEX idx_places_area_anchor_active ON places (area_id, is_anchor_candidate, is_active);
CREATE INDEX idx_places_area_type_active ON places (area_id, place_type, is_active);
CREATE INDEX idx_places_last_synced_at ON places (last_synced_at);
CREATE INDEX idx_area_tags_tag_area ON area_tags (tag_id, area_id);
CREATE INDEX idx_place_tags_tag_place ON place_tags (tag_id, place_id);
