CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_id BIGINT NOT NULL,
    anchor_place_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(2000),
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_courses_area FOREIGN KEY (area_id) REFERENCES areas (id),
    CONSTRAINT fk_courses_anchor_place FOREIGN KEY (anchor_place_id) REFERENCES places (id)
);

CREATE TABLE course_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,
    item_order INTEGER NOT NULL,
    item_role VARCHAR(20) NOT NULL,
    CONSTRAINT fk_course_items_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_items_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT ck_course_items_item_order_non_negative CHECK (item_order >= 0),
    CONSTRAINT ck_course_items_item_role CHECK (item_role IN ('ACTIVITY', 'MEAL', 'CAFE')),
    CONSTRAINT uk_course_items_course_order UNIQUE (course_id, item_order)
);

CREATE TABLE course_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    weight INTEGER NOT NULL,
    CONSTRAINT fk_course_tags_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT fk_course_tags_tag FOREIGN KEY (tag_id) REFERENCES tags (id),
    CONSTRAINT uk_course_tags_course_tag UNIQUE (course_id, tag_id),
    CONSTRAINT ck_course_tags_weight CHECK (weight BETWEEN 0 AND 100)
);

CREATE TABLE course_companion_types (
    course_id BIGINT NOT NULL,
    companion_type VARCHAR(20) NOT NULL,
    CONSTRAINT fk_course_companion_types_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT pk_course_companion_types PRIMARY KEY (course_id, companion_type),
    CONSTRAINT ck_course_companion_types_value CHECK (companion_type IN ('FRIEND', 'LOVER', 'FAMILY'))
);

CREATE TABLE course_time_slots (
    course_id BIGINT NOT NULL,
    time_slot VARCHAR(20) NOT NULL,
    CONSTRAINT fk_course_time_slots_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT pk_course_time_slots PRIMARY KEY (course_id, time_slot),
    CONSTRAINT ck_course_time_slots_value CHECK (time_slot IN ('MORNING', 'AFTERNOON', 'NIGHT'))
);

CREATE TABLE course_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    impression_count BIGINT NOT NULL DEFAULT 0,
    view_count BIGINT NOT NULL DEFAULT 0,
    selection_count BIGINT NOT NULL DEFAULT 0,
    save_count BIGINT NOT NULL DEFAULT 0,
    share_count BIGINT NOT NULL DEFAULT 0,
    last_viewed_at TIMESTAMP,
    last_selected_at TIMESTAMP,
    last_saved_at TIMESTAMP,
    last_shared_at TIMESTAMP,
    CONSTRAINT fk_course_stats_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT uk_course_stats_course UNIQUE (course_id),
    CONSTRAINT ck_course_stats_counts_non_negative CHECK (impression_count >= 0 AND view_count >= 0 AND selection_count >= 0 AND save_count >= 0 AND share_count >= 0)
);

CREATE INDEX idx_courses_area_published ON courses (area_id, is_published);
CREATE INDEX idx_courses_anchor_place ON courses (anchor_place_id);
CREATE INDEX idx_course_items_course_order ON course_items (course_id, item_order);
CREATE INDEX idx_course_items_place ON course_items (place_id);
CREATE INDEX idx_course_tags_tag_course ON course_tags (tag_id, course_id);
CREATE INDEX idx_course_stats_selection_count ON course_stats (selection_count);
