CREATE TABLE place_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    view_count BIGINT NOT NULL DEFAULT 0,
    selection_count BIGINT NOT NULL DEFAULT 0,
    save_count BIGINT NOT NULL DEFAULT 0,
    share_count BIGINT NOT NULL DEFAULT 0,
    last_viewed_at TIMESTAMP,
    last_selected_at TIMESTAMP,
    last_saved_at TIMESTAMP,
    last_shared_at TIMESTAMP,
    CONSTRAINT fk_place_stats_place FOREIGN KEY (place_id) REFERENCES places (id) ON DELETE CASCADE,
    CONSTRAINT uk_place_stats_place UNIQUE (place_id),
    CONSTRAINT ck_place_stats_counts_non_negative CHECK (view_count >= 0 AND selection_count >= 0 AND save_count >= 0 AND share_count >= 0)
);

INSERT INTO place_stats (place_id, selection_count, last_selected_at)
SELECT id, selection_count, last_selected_at FROM places;

CREATE TABLE course_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    view_count BIGINT NOT NULL DEFAULT 0,
    selection_count BIGINT NOT NULL DEFAULT 0,
    save_count BIGINT NOT NULL DEFAULT 0,
    share_count BIGINT NOT NULL DEFAULT 0,
    last_viewed_at TIMESTAMP,
    last_selected_at TIMESTAMP,
    last_saved_at TIMESTAMP,
    last_shared_at TIMESTAMP,
    CONSTRAINT fk_course_stats_course FOREIGN KEY (course_id) REFERENCES courses (id) ON DELETE CASCADE,
    CONSTRAINT uk_course_stats_course UNIQUE (course_id),
    CONSTRAINT ck_course_stats_counts_non_negative CHECK (view_count >= 0 AND selection_count >= 0 AND save_count >= 0 AND share_count >= 0)
);

INSERT INTO course_stats (course_id, selection_count, last_selected_at)
SELECT id, selection_count, last_selected_at FROM courses;

ALTER TABLE places
    DROP COLUMN selection_count,
    DROP COLUMN last_selected_at;

ALTER TABLE courses
    DROP COLUMN selection_count,
    DROP COLUMN last_selected_at;

CREATE INDEX idx_place_stats_selection_count ON place_stats (selection_count);
CREATE INDEX idx_course_stats_selection_count ON course_stats (selection_count);
