CREATE TABLE place_collection_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(30) NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    search_type VARCHAR(20) NOT NULL,
    category_group_code VARCHAR(10),
    query VARCHAR(200),
    place_type VARCHAR(20) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_collection_profiles_provider_code UNIQUE (provider, code),
    CONSTRAINT ck_collection_profiles_search CHECK (
        (search_type = 'CATEGORY' AND category_group_code IS NOT NULL AND query IS NULL)
        OR (search_type = 'KEYWORD' AND category_group_code IS NULL AND query IS NOT NULL)
    ),
    CONSTRAINT ck_collection_profiles_place_type CHECK (place_type IN ('ACTIVITY', 'MEAL', 'CAFE'))
);

CREATE TABLE place_collection_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_job_id BIGINT,
    area_id BIGINT NOT NULL,
    collection_profile_id BIGINT NOT NULL,
    profile_code VARCHAR(50) NOT NULL,
    search_type VARCHAR(20) NOT NULL,
    category_group_code VARCHAR(10),
    query VARCHAR(200),
    place_type VARCHAR(20) NOT NULL,
    min_latitude NUMERIC(10, 7) NOT NULL,
    min_longitude NUMERIC(10, 7) NOT NULL,
    max_latitude NUMERIC(10, 7) NOT NULL,
    max_longitude NUMERIC(10, 7) NOT NULL,
    depth INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'READY',
    total_count INTEGER,
    pageable_count INTEGER,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    error_message VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_collection_jobs_parent FOREIGN KEY (parent_job_id) REFERENCES place_collection_jobs (id),
    CONSTRAINT fk_collection_jobs_area FOREIGN KEY (area_id) REFERENCES areas (id),
    CONSTRAINT fk_collection_jobs_profile FOREIGN KEY (collection_profile_id) REFERENCES place_collection_profiles (id),
    CONSTRAINT ck_collection_jobs_bounds CHECK (min_latitude < max_latitude AND min_longitude < max_longitude),
    CONSTRAINT ck_collection_jobs_depth CHECK (depth >= 0),
    CONSTRAINT ck_collection_jobs_status CHECK (status IN ('READY', 'RUNNING', 'COMPLETED', 'PARTIAL', 'SPLIT', 'FAILED'))
);

CREATE TABLE place_category_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(100) NOT NULL,
    target_place_type VARCHAR(20) NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_place_category_rules_keyword UNIQUE (keyword),
    CONSTRAINT ck_place_category_rules_place_type CHECK (target_place_type IN ('ACTIVITY', 'MEAL', 'CAFE'))
);

CREATE INDEX idx_collection_profiles_provider_active ON place_collection_profiles (provider, is_active);
CREATE INDEX idx_collection_jobs_status ON place_collection_jobs (status);
CREATE INDEX idx_collection_jobs_area_profile ON place_collection_jobs (area_id, collection_profile_id);
CREATE INDEX idx_place_category_rules_active_priority ON place_category_rules (is_active, priority DESC, id);
