ALTER TABLE tags
    ADD COLUMN display_name VARCHAR(100),
    ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN display_order INTEGER NOT NULL DEFAULT 0;

UPDATE tags
SET display_name = code
WHERE display_name IS NULL;

ALTER TABLE tags
    ALTER COLUMN display_name SET NOT NULL;

CREATE TABLE tag_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_id BIGINT NOT NULL,
    option_name VARCHAR(100) NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_tag_options_tag FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE,
    CONSTRAINT uk_tag_options_tag_name UNIQUE (tag_id, option_name),
    CONSTRAINT ck_tag_options_display_order_non_negative CHECK (display_order >= 0)
);

CREATE INDEX idx_tags_active_order ON tags (is_active, display_order);
CREATE INDEX idx_tag_options_tag_active_order ON tag_options (tag_id, is_active, display_order);
