CREATE TABLE openai_batch_tagging_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    openai_batch_id VARCHAR(100),
    status VARCHAR(20) NOT NULL,
    requested_count INTEGER NOT NULL,
    error_message VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_openai_batch_tagging_jobs_openai_batch UNIQUE (openai_batch_id),
    CONSTRAINT ck_openai_batch_tagging_jobs_status CHECK (status IN ('SUBMITTING', 'SUBMITTED', 'COMPLETED', 'FAILED'))
);

ALTER TABLE place_collection_temp
    ADD COLUMN ai_batch_job_id BIGINT;

ALTER TABLE place_collection_temp
    ADD CONSTRAINT fk_place_collection_temp_ai_batch_job
    FOREIGN KEY (ai_batch_job_id) REFERENCES openai_batch_tagging_jobs (id);

CREATE INDEX idx_place_collection_temp_ai_batch_job_id ON place_collection_temp (ai_batch_job_id, id);
