package com.junsang.course_backend.domain.place.collection.entity;

public enum PlaceRefinementErrorCode {
    KAKAO_API_KEY_NOT_CONFIGURED,
    KAKAO_LOCAL_API_REQUEST_FAILED,
    KAKAO_LOCAL_API_EMPTY_RESPONSE,
    KAKAO_RESULT_LIMIT_EXCEEDED,
    KAKAO_COLLECTION_PROCESSING_FAILED,

    NAVER_RESULT_NOT_FOUND,
    NAVER_PLACE_NOT_MATCHED,
    NAVER_PLACE_AMBIGUOUS,
    NAVER_POSSIBLE_RELOCATION,
    NAVER_SEARCH_API_KEY_NOT_CONFIGURED,
    NAVER_LOCAL_API_REQUEST_FAILED,
    NAVER_LOCAL_API_EMPTY_RESPONSE,
    NAVER_BLOG_API_REQUEST_FAILED,
    NAVER_BLOG_API_EMPTY_RESPONSE,
    NAVER_API_REQUEST_FAILED,

    OPENAI_API_KEY_NOT_CONFIGURED,
    OPENAI_API_REQUEST_FAILED,
    OPENAI_API_EMPTY_RESPONSE,
    OPENAI_BATCH_SUBMISSION_FAILED,
    OPENAI_BATCH_REMOTE_FAILED,

    AI_NO_ACTIVE_TAGS,
    AI_RESPONSE_PARSE_FAILED,
    AI_RESPONSE_TARGET_MISMATCH,
    AI_TAG_VALIDATION_FAILED,
    AI_BATCH_OUTPUT_INVALID,
    AI_RESPONSE_INVALID,

    INVALID_PROCESSING_STEP,
    UNEXPECTED_ERROR
}
